### ISSUE TITLE
Support Java DSL for camel-k .java files in VSCode

### ISSUE THREAD

**Issue by rafaeltuelho** [camel-tooling/camel-lsp-client-vscode#117]
when editing a `.java` file in camel-k style (no maven/eclipse project structure) the Camel Language Server does not recognize Java DSL (code completion)...

![image](https://user-images.githubusercontent.com/39063/62665202-d9901280-b954-11e9-9529-ac944b2d6dc7.png)

**Comment by apupier** [comment]
Thanks for reporting the feature request. The Camel Language Server is providing support only for the Camel URI part currently. The java APi by itself was supposed to be provided by the IDE (or another extension of the IDE)
linking to the Camel Language Server issue dealing with Camel-K  https://github.com/camel-tooling/camel-language-server/issues/163

Personally, i think the real problem is that there is no Camel-K project structure provided but I know that I'm alone to think that.

That said, technically it might be possible to call the jdt.ls language server and create a fake project in the background to get completion.

**Comment by apupier** [comment]
tracked here https://issues.redhat.com/browse/FUSETOOLS2-81

current possibilities for standalone Java files in VS Code: 
![completionJavaStandaloneFile](https://user-images.githubusercontent.com/1105127/70732195-44d56100-1d08-11ea-8b53-b9e34267fa5a.gif)

**Comment by rafaeltuelho** [comment]
Wow! That's awesome @apupier!!!

**Comment by apupier** [comment]
It has been implemented in vscode-camelk and relies on vscode-java features.
see https://issues.redhat.com/browse/FUSETOOLS2-81
Using latest VS Code Camel K will automatically add the camel-core-engine dependencies to the classpath of the standalone Camel K java file.

so available in 0.0.11 of https://marketplace.visualstudio.com/items?itemName=redhat.vscode-camelk (you need the latest VS Code version)
