### ISSUE TITLE
[ENH] Improving activating whitelist support for Java DSL

### ISSUE THREAD

**Issue by paoloantinori** [camel-tooling/camel-lsp-client-vscode#50]
According to yesterday's article, there is currently a set of pre-requisites for the functionality to be enabled:

- The filename needs to end with `.java`.
- The file needs to contain `camel` written somewhere.
- The Camel URI String needs to be used directly as a parameter of the `RouteBuilder.from` or `RouteBuilder.to` methods (which means no space, no variable).

This is understood but it would be useful exposing the user the logic to activate the functionality.

I assume the `.java` suffix is an hard constraint, despite I think it should be useful to allow a way to enable the plugin also on disposable temporary new files, that don't have any file name yet.

The most limiting constraint is the `camel` keyword requirement. I was about to suggest to switch to `route`, but at that point, I've realised that probably the real feature would be to allow the user to specify the regexp/GLOB/keywords they like.

**Comment by apupier** [comment]
I don't think that _camel_ keyword is a big requirements as it will be part of import package for _RouteBuilder_ which will be a very common use case to have in the file.

I would like to avoid to have something specific to users to specify when to activate it in client side or not and have a smarter detection on Language server side.
Having it on client side means that we will need to develop it X times, X being the number of IDE clients (currently 3).

For smarter detection:
- other heuristics?
- see if Camel built-in parsers can be used
- see if we put a dependency on jdt.ls and reuse the classpath mechanism available so that we can detect the exact correct class available.

The goal was to release a first version with some constraints and see the feedback from users if we really need to go further or not, and with which priority.

**Comment by paoloantinori** [comment]
Ah, sorry, I had misread the article and thought that `camel` was a requirement in the file name, not just to be present in the content of the file.

That was probably the main point in my enhancement request, so since it was never valid, we can even ignore this request.

I'd personally like the idea to be able to have the support also for an in-progress no name file, but that's not super important.

**Comment by apupier** [comment]
> to have the support also for an in-progress no name file

I don't think that a lot of IDEs are able to provide great support on non-named file; I just tried with VS Code and there is not even syntax coloring for Java. On Eclipse Desktop, you are forced to provide a name first.
